name = "MatrixLabTools"
uuid = "ff65f36f-f85e-49fc-906c-9f9c7b02249d"
repo = "https://github.com/MatrixLabTools/PackageRegistry.git"

description = """
Julia package repository for packages related to QM/MM for matrix systems.
"""

[packages]
"76415700-ec45-11e8-0f65-f1df3c899b21" = {name = "PotentialCalculation", path = "packages/PotentialCalculation"}
"ec7fb60e-ec45-11e8-1605-2d81b01dfc43" = {name = "PotentialFitting", path = "packages/PotentialFitting"}
"e899a7e1-cf22-409b-b35c-84b9d10c2c8e" = {name = "PotentialDB", path = "packages/PotentialDB"}
